### PR TITLE
Comments updates

### PR DESCRIPTION
**Pull request by remedcu**
Task List:

- [x] Comments Updated
- [x] Returns params updated as per NatSpec
- [ ] fundAppeal type of party check optimized
- [x] RAB Pragma Updated

### CODE REVIEW

**Comment by remedcu** [comment]
@mtsalenc

Apart from some comments update and RAB Pragma update, the only logical change is on the type of party check, in `fundAppeal` function in line 332.

**Comment by clesaege** [comment]
This changes the state. If it's not broken don't fix it.

**Comment by mtsalenc** [comment]
I think the PR can still benefit from the non-state changing fixes (e.g the pragma and comments update) so I am reopening this.

Can you make a commit removing changes to logic/state?

**Comment by remedcu** [comment]
Already done in commit d7941c0

**Pull request merged**
